package kick

import (
	"context"
	"crypto/tls"
	"errors"
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"os/signal"
	"sync/atomic"
	"time"

	"golang.org/x/crypto/acme/autocert"
)

// A Server defines parameters for running an HTTP server.
// Its fields must be set prior to calling Build or
// ListenAndServe, and should not be modified afterwards.
// Once closed, a Server cannot be restarted.
type Server struct {
	// Addr is the TCP address to listen on, <addr>:<port>.
	Addr string

	// Timeouts are transferred as-is to the corresponding
	// http.Server fields, see that type's fields documentation
	// for details.
	ReadTimeout       time.Duration
	ReadHeaderTimeout time.Duration
	WriteTimeout      time.Duration
	IdleTimeout       time.Duration

	// MaxHeaderBytes is transferred as-is to the corresponding
	// http.Server field, see that field's documentation for
	// details.
	MaxHeaderBytes int

	// Handler is transferred as-is to the corresponding http.Server field, see
	// that field's documentation for details.
	Handler http.Handler

	// TLS configures the TLS settings of the server.
	TLS *TLSConfig

	// GracefulShutdown enables the graceful shutdown of the
	// server on configured signals, or when the context passed
	// to ListenAndServe is canceled. If nil, there is no automatic
	// graceful shutdown.
	GracefulShutdown *GracefulShutdownConfig

	// ConnStateHook and ServerStateHook are optional function
	// callbacks that get called when the connection or the
	// server (respectively) transition from one state to the
	// next. ConnStateHook is transferred as-is to the
	// http.Server.ConnState field. See the ServerState type
	// and associated constants for details about the
	// ServerStateHook.
	ConnStateHook   func(net.Conn, http.ConnState)
	ServerStateHook func(*http.Server, ServerState)

	// BaseContext and ConnContext are optional functions that get called to
	// generate the base context of the server, or the initial context for
	// a connection. They are both transferred as-is to the http.Server's
	// corresponding fields.
	BaseContext func(net.Listener) context.Context
	ConnContext func(ctx context.Context, c net.Conn) context.Context

	// ErrorLog is the logger used to log errors that may occur
	// while serving connections. It uses the standard library's
	// logger as this is what is supported by the http.Server,
	// but many popular logging packages provide adapters for
	// that logger.
	ErrorLog *log.Logger

	// generated by Build
	srv   *http.Server
	built bool
	// handled by s.transit, atomically
	state int32
}

// Build generates the properly configured http.Server and
// net.Listener from the Server struct. Everything is ready
// to run by calling Serve on the returned http.Server and
// passing it the returned net.Listener.
func (s *Server) Build() error {
	if s.built {
		return errors.New("server already built")
	}
	return s.build()
}

func (s *Server) build() error {
	s.built = true

	tc, err := buildTLS(s)
	if err != nil {
		return err
	}

	srv, err := buildHTTPServer(s)
	if err != nil {
		return err
	}

	if s.TLS != nil && s.TLS.DisableHTTP2 && srv.TLSNextProto == nil {
		srv.TLSNextProto = make(map[string]func(*http.Server, *tls.Conn, http.Handler))
	}

	srv.TLSConfig = tc
	s.srv = srv
	return nil
}

// HTTPServer returns the generated http.Server. It calls
// Build if it hasn't been called yet.
func (s *Server) HTTPServer() (*http.Server, error) {
	if !s.built {
		if err := s.build(); err != nil {
			return nil, err
		}
	}
	return s.srv, nil
}

// ListenAndServe calls Build if the Server hasn't been
// generated yet, and then starts listening and serving
// connections. It returns the error returned from
// http.Server.ListenAndServe[TLS], which is always non-nil but is
// http.ErrServerClosed if the server was closed explicitly.
//
// If GracefulShutdown is configured, the server is shutdown
// gracefully when the ctx is cancelled or the configured
// signals are caught, otherwise the server is closed when
// the ctx is cancelled.
func (s *Server) ListenAndServe(ctx context.Context) error {
	if !s.built {
		if err := s.build(); err != nil {
			return err
		}
	}
	if atomic.LoadInt32(&s.state) == int32(StateClosed) {
		return http.ErrServerClosed
	}

	ctx, cancel := context.WithCancel(ctx)
	defer cancel()

	conf := s.GracefulShutdown
	if conf != nil {
		if len(conf.Signals) > 0 {
			// listen for signals to trigger graceful shutdown
			ch := make(chan os.Signal, 1)
			signal.Notify(ch, conf.Signals...)
			go func() {
				<-ch
				cancel()
			}()

			// unblock the goroutine on exit if cancelled by other means
			defer func() {
				signal.Stop(ch)
				close(ch)
			}()
		}
	}

	srv := s.srv

	s.transit(StateNew)
	defer s.transit(StateClosed)

	var lasErr error
	ch := make(chan struct{})
	go func() {
		defer close(ch)

		s.transit(StateListening)
		if srv.TLSConfig != nil {
			lasErr = srv.ListenAndServeTLS("", "")
			return
		}
		lasErr = srv.ListenAndServe()
	}()

	select {
	case <-ctx.Done():
		// initiate the graceful shutdown or explicit close request
		var err error

		if conf != nil {
			// transition before calling shutdown, as shutdown hooks are called
			// in goroutines and may end up calling the server hooks *after*
			// StateClosed has been sent.
			s.transit(StateShutdown)

			sdctx := context.Background()
			if conf.Timeout != 0 {
				var cancel func()
				sdctx, cancel = context.WithTimeout(context.Background(), conf.Timeout)
				defer cancel()
			}
			if conf.ShutdownContext != nil {
				sdctx = conf.ShutdownContext(sdctx)
			}
			err = srv.Shutdown(sdctx)
		} else {
			err = srv.Close()
		}
		<-ch

		// if there is no Shutdown or Close error, then return the ctx.Err
		if err == nil {
			err = ctx.Err()
		}
		return err

	case <-ch:
		// if srv.ListenAndServe[TLS] returned by itself, then it failed
		// for some reason, return that error.
		return lasErr
	}
}

func (s *Server) transit(to ServerState) {
	atomic.StoreInt32(&s.state, int32(to))
	if s.ServerStateHook != nil {
		s.ServerStateHook(s.srv, to)
	}
}

// ServerState defines the various states the Server may be in.
type ServerState int32

const (
	// StateNew represents a new Server that is expected to start
	// listening and serving immediately. Servers start at this
	// state and transition to StateListening or StateClosed.
	StateNew ServerState = iota

	// StateListening represents a Server that will start listening
	// and serving connections. From that state, it may transition
	// to StateShutdown or StateClosed.
	StateListening

	// StateShutdown represents a Server that started a graceful
	// shutdown. It may only transition to StateClosed.
	StateShutdown

	// StateClosed represents a closed Server. This is a terminal
	// state.
	StateClosed
)

var stringServerState = [...]string{
	StateNew:       "StateNew",
	StateListening: "StateListening",
	StateShutdown:  "StateShutdown",
	StateClosed:    "StateClosed",
}

func (s ServerState) String() string {
	if s < 0 || int(s) >= len(stringServerState) {
		return fmt.Sprintf("<unknown:%d>", s)
	}
	return stringServerState[s]
}

// TLSMode is the type of the predefined TLS configuration modes.
type TLSMode int

// List of supported TLS modes.
const (
	TLSDefault TLSMode = iota
	TLSIntermediate
	TLSModern
)

var stringTLSMode = [...]string{
	TLSDefault:      "TLSDefault",
	TLSIntermediate: "TLSIntermediate",
	TLSModern:       "TLSModern",
}

func (m TLSMode) String() string {
	if m < 0 || int(m) >= len(stringTLSMode) {
		return fmt.Sprintf("<unknown:%d>", m)
	}
	return stringTLSMode[m]
}

// TLSConfig configures the TLS settings of the server.
// See https://wiki.mozilla.org/Security/Server_Side_TLS and
// https://blog.cloudflare.com/exposing-go-on-the-internet/
// for more details.
type TLSConfig struct {
	// Mode is the TLS mode to use. It is just a hint passed to the
	// TLS builder, and is a moving target as cryptography evolves
	// and so do configuration recommendations.
	Mode TLSMode

	// AutoCert indicates if the TLS certificate should be automatically
	// generated and renewed.
	AutoCert bool

	// AutoCertCacheDir is the directory path where auto-generated
	// certificates are stored. This should be a secure directory,
	// not exposed to the internet, but the process running the server
	// must have write access to it. If the directory does not exist,
	// it will be created with 0700 permissions.
	AutoCertCacheDir string

	// AutoCertExactHosts is the list of host names that will be allowed
	// by the generated certificate. Only exact matches are supported,
	// no wildcards.
	AutoCertExactHosts []string

	// AutoCertContactEmail is an optional email address that CAs should use
	// to notify about issues with certificates.
	AutoCertContactEmail string

	// If AutoCert is false, CertFile and KeyFile are used as
	// certificate files.
	CertFile string
	KeyFile  string

	// DisableHTTP2 indicates that the TLS server should not support
	// HTTP/2. By default, a Server with a TLSConfig would automatically
	// support HTTP/2, but it may be useful in certain conditions to
	// disable that automatic support (e.g. for Websockets, at least
	// until those are supported on HTTP/2).
	//
	// This is an option on TLSConfig and not directly on the Server,
	// because automatic HTTP/2 support is only enabled for TLS servers.
	DisableHTTP2 bool

	_ struct{} // prevent unkeyed struct creation
}

// GracefulShutdownConfig configures the graceful shutdown
// of the server.
type GracefulShutdownConfig struct {
	// Timeout indicates the time allowed for graceful shutdown
	// to proceed.
	Timeout time.Duration

	// ShutdownContext is an optional function that can be used to control
	// cancellation of the shutdown process, in addition to the Timeout field. If
	// set, it is called with the initial shutdown context (which is
	// context.Background or a context with the specified Timeout if it is set).
	// The returned context must not be nil, and it is the context used to call
	// Server.Shutdown.
	ShutdownContext func(ctx context.Context) context.Context

	// Signals is the list of OS signals that initiate a
	// graceful shutdown when caught.
	Signals []os.Signal

	_ struct{} // prevent unkeyed struct creation
}

func buildTLS(s *Server) (*tls.Config, error) {
	var tc *tls.Config

	if s.TLS == nil {
		return nil, nil
	}

	if s.TLS.AutoCert {
		tc = configureTLSAutoCert(s.TLS)
	} else {
		tc = new(tls.Config)
	}

	switch s.TLS.Mode {
	case TLSDefault:
		// zero-value of tls.Config requested

	case TLSIntermediate, TLSModern:
		// Only use curves which have assembly implementations
		tc.CurvePreferences = []tls.CurveID{
			tls.CurveP256,
			tls.X25519,
		}
		if s.TLS.Mode == TLSIntermediate {
			break
		}

		tc.MinVersion = tls.VersionTLS12
		tc.CipherSuites = []uint16{
			tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
			tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
			tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
			tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
			tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
			tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,

			// Best disabled, as they don't provide Forward Secrecy,
			// but might be necessary for some clients
			// tls.TLS_RSA_WITH_AES_256_GCM_SHA384,
			// tls.TLS_RSA_WITH_AES_128_GCM_SHA256,
		}

	default:
		return nil, fmt.Errorf("tls: unsupported TLS mode: %d", s.TLS.Mode)
	}

	if !s.TLS.AutoCert {
		if err := configureTLSCertificate(tc, s.TLS.CertFile, s.TLS.KeyFile); err != nil {
			return nil, err
		}
	}

	return tc, nil
}

func configureTLSAutoCert(config *TLSConfig) *tls.Config {
	m := &autocert.Manager{
		Cache:      autocert.DirCache(config.AutoCertCacheDir),
		Prompt:     autocert.AcceptTOS,
		HostPolicy: autocert.HostWhitelist(config.AutoCertExactHosts...),
		Email:      config.AutoCertContactEmail,
	}
	return m.TLSConfig()
}

func configureTLSCertificate(tc *tls.Config, certFile, keyFile string) error {
	// certfile and keyfile are required
	if certFile == "" || keyFile == "" {
		return errors.New("tls: certificate and key files must be set")
	}

	var err error
	tc.Certificates = make([]tls.Certificate, 1)
	tc.Certificates[0], err = tls.LoadX509KeyPair(certFile, keyFile)
	return err
}

func buildHTTPServer(s *Server) (*http.Server, error) {
	srv := &http.Server{
		Addr:              s.Addr,
		Handler:           s.Handler,
		ReadTimeout:       s.ReadTimeout,
		ReadHeaderTimeout: s.ReadHeaderTimeout,
		WriteTimeout:      s.WriteTimeout,
		IdleTimeout:       s.IdleTimeout,
		MaxHeaderBytes:    s.MaxHeaderBytes,
		ConnState:         s.ConnStateHook,
		ErrorLog:          s.ErrorLog,
		BaseContext:       s.BaseContext,
		ConnContext:       s.ConnContext,
	}
	return srv, nil
}
