package server

import (
	"context"
	"crypto/tls"
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"os/signal"
	"sync/atomic"
	"time"

	"codeberg.org/mna/karbur/errors"
	"golang.org/x/crypto/acme/autocert"
)

// A Server defines parameters for running an HTTP server.
// Its fields must be set prior to calling Build, HTTPServer or
// ListenAndServe, and should not be modified afterwards, but
// further configuration of the built *http.Server can be done
// by calling HTTPServer before calling ListenAndServe.
// Once closed, a Server cannot be restarted.
type Server struct {
	// Addr is the TCP address to listen on, <addr>:<port>.
	Addr string

	// Timeouts are transferred as-is to the corresponding
	// http.Server fields, see that type's fields documentation
	// for details.
	ReadTimeout       time.Duration
	ReadHeaderTimeout time.Duration
	WriteTimeout      time.Duration
	IdleTimeout       time.Duration

	// MaxHeaderBytes is transferred as-is to the corresponding
	// http.Server field, see that field's documentation for
	// details.
	MaxHeaderBytes int

	// Protocols is the set of protocols accepted by the server.
	// It is transferred as-is to the corresponding http.Server
	// field, see that field's documentation for details.
	Protocols *http.Protocols

	// Handler is transferred as-is to the corresponding http.Server field, see
	// that field's documentation for details.
	Handler http.Handler

	// HTTP2Config configures the HTTP2 support. It is transferred
	// as-is to the corresponding http.Server fields, see that type's
	// fields documentation for details.
	HTTP2Config *http.HTTP2Config

	// Certs configure TLS certificates for the server.
	Certs *Certs

	// GracefulShutdown enables the graceful shutdown of the
	// server on configured signals, or when the context passed
	// to ListenAndServe is canceled. If nil, there is no automatic
	// graceful shutdown.
	GracefulShutdown *GracefulShutdownConfig

	// ConnStateHook and ServerStateHook are optional function
	// callbacks that get called when the connection or the
	// server (respectively) transition from one state to the
	// next. ConnStateHook is transferred as-is to the
	// http.Server.ConnState field. See the ServerState type
	// and associated constants for details about the
	// ServerStateHook.
	ConnStateHook   func(net.Conn, http.ConnState)
	ServerStateHook func(*http.Server, ServerState)

	// BaseContext and ConnContext are optional functions that get called to
	// generate the base context of the server, or the initial context for
	// a connection. They are both transferred as-is to the http.Server's
	// corresponding fields.
	BaseContext func(net.Listener) context.Context
	ConnContext func(ctx context.Context, c net.Conn) context.Context

	// ErrorLog is the logger used to log errors that may occur
	// while serving connections. It uses the standard library's
	// logger as this is what is supported by the http.Server,
	// but many popular logging packages provide adapters for
	// that logger.
	ErrorLog *log.Logger

	// generated by Build
	srv   *http.Server
	built bool
	// handled by s.transit, atomically
	state int32
}

// Build generates the properly configured http.Server.
func (s *Server) Build() error {
	if s.built {
		return errors.New("server already built")
	}
	return s.build()
}

func (s *Server) build() error {
	s.built = true

	tc, err := buildTLS(s)
	if err != nil {
		return err
	}

	srv, err := buildHTTPServer(s, tc)
	if err != nil {
		return err
	}

	s.srv = srv
	return nil
}

// HTTPServer returns the generated http.Server. It calls
// Build if it hasn't been called yet.
func (s *Server) HTTPServer() (*http.Server, error) {
	if !s.built {
		if err := s.build(); err != nil {
			return nil, err
		}
	}
	return s.srv, nil
}

// ListenAndServe calls Build if the Server hasn't been
// generated yet, and then starts listening and serving
// connections. It returns the error returned from
// http.Server.ListenAndServe[TLS], which is always non-nil but is
// http.ErrServerClosed if the server was closed explicitly.
//
// If GracefulShutdown is configured, the server is shutdown
// gracefully when the ctx is cancelled or the configured
// signals are caught, otherwise the server is closed when
// the ctx is cancelled.
func (s *Server) ListenAndServe(ctx context.Context) error {
	if !s.built {
		if err := s.build(); err != nil {
			return err
		}
	}
	if atomic.LoadInt32(&s.state) == int32(StateClosed) {
		return http.ErrServerClosed
	}

	ctx, cancel := context.WithCancel(ctx)
	defer cancel()

	conf := s.GracefulShutdown
	if conf != nil && len(conf.Signals) > 0 {
		// listen for signals to trigger graceful shutdown
		var stopSignal context.CancelFunc
		ctx, stopSignal = signal.NotifyContext(ctx, conf.Signals...)
		defer stopSignal()
	}

	srv := s.srv

	s.transit(StateNew)
	defer s.transit(StateClosed)

	var lasErr error
	ch := make(chan struct{})
	go func() {
		defer close(ch)

		s.transit(StateListening)
		if srv.TLSConfig != nil {
			lasErr = srv.ListenAndServeTLS("", "")
			return
		}
		lasErr = srv.ListenAndServe()
	}()

	select {
	case <-ctx.Done():
		// initiate the graceful shutdown or explicit close request
		var err error

		if conf != nil {
			// transition before calling shutdown, as shutdown hooks are called
			// in goroutines and may end up calling the server hooks *after*
			// StateClosed has been sent.
			s.transit(StateShutdown)

			sdctx := context.Background()
			if conf.Timeout != 0 {
				var cancel func()
				sdctx, cancel = context.WithTimeout(sdctx, conf.Timeout)
				defer cancel()
			}
			if conf.ShutdownContext != nil {
				sdctx = conf.ShutdownContext(sdctx)
			}
			err = srv.Shutdown(sdctx)
		} else {
			err = srv.Close()
		}
		<-ch

		// if there is no Shutdown or Close error, then return the ctx.Err
		if err == nil {
			err = ctx.Err()
		}
		return err

	case <-ch:
		// if srv.ListenAndServe[TLS] returned by itself, then it failed
		// for some reason, return that error.
		return lasErr
	}
}

func (s *Server) transit(to ServerState) {
	atomic.StoreInt32(&s.state, int32(to))
	if s.ServerStateHook != nil {
		s.ServerStateHook(s.srv, to)
	}
}

// ServerState defines the various states the Server may be in.
type ServerState int32

const (
	// StateNew represents a new Server that is expected to start
	// listening and serving immediately. Servers start at this
	// state and transition to StateListening or StateClosed.
	StateNew ServerState = iota

	// StateListening represents a Server that will start listening
	// and serving connections. From that state, it may transition
	// to StateShutdown or StateClosed.
	StateListening

	// StateShutdown represents a Server that started a graceful
	// shutdown. It may only transition to StateClosed.
	StateShutdown

	// StateClosed represents a closed Server. This is a terminal
	// state.
	StateClosed
)

var stringServerState = [...]string{
	StateNew:       "StateNew",
	StateListening: "StateListening",
	StateShutdown:  "StateShutdown",
	StateClosed:    "StateClosed",
}

func (s ServerState) String() string {
	if s < 0 || int(s) >= len(stringServerState) {
		return fmt.Sprintf("<unknown:%d>", s)
	}
	return stringServerState[s]
}

// Certs configures the TLS certificates of the server.
type Certs struct {
	// AutoCert indicates if the TLS certificate should be automatically
	// generated and renewed.
	AutoCert bool

	// AutoCertCacheDir is the directory path where auto-generated
	// certificates are stored. This should be a secure directory,
	// not exposed to the internet, but the process running the server
	// must have write access to it. If the directory does not exist,
	// it will be created with 0700 permissions.
	AutoCertCacheDir string

	// AutoCertExactHosts is the list of host names that will be allowed
	// by the generated certificate. Only exact matches are supported,
	// no wildcards.
	AutoCertExactHosts []string

	// AutoCertContactEmail is an optional email address that CAs should use
	// to notify about issues with certificates.
	AutoCertContactEmail string

	// If AutoCert is false, CertFile and KeyFile are used as
	// certificate files.
	CertFile string
	KeyFile  string

	_ struct{} // prevent unkeyed struct creation
}

// GracefulShutdownConfig configures the graceful shutdown
// of the server.
type GracefulShutdownConfig struct {
	// Timeout indicates the time allowed for graceful shutdown
	// to proceed.
	Timeout time.Duration

	// ShutdownContext is an optional function that can be used to control
	// cancellation of the shutdown process, in addition to the Timeout field. If
	// set, it is called with the initial shutdown context (which is
	// context.Background or a context with the specified Timeout if it is set).
	// The returned context must not be nil, and it is the context used to call
	// Server.Shutdown.
	ShutdownContext func(ctx context.Context) context.Context

	// Signals is the list of OS signals that initiate a
	// graceful shutdown when caught.
	Signals []os.Signal

	_ struct{} // prevent unkeyed struct creation
}

func buildTLS(s *Server) (*tls.Config, error) {
	if s.Certs == nil {
		return nil, nil
	}

	if s.Certs.AutoCert {
		return configureTLSAutoCert(s.Certs), nil
	}

	tc := new(tls.Config)
	if err := configureTLSCertificate(tc, s.Certs.CertFile, s.Certs.KeyFile); err != nil {
		return nil, err
	}
	return tc, nil
}

func configureTLSAutoCert(config *Certs) *tls.Config {
	m := &autocert.Manager{
		Cache:      autocert.DirCache(config.AutoCertCacheDir),
		Prompt:     autocert.AcceptTOS,
		HostPolicy: autocert.HostWhitelist(config.AutoCertExactHosts...),
		Email:      config.AutoCertContactEmail,
	}
	return m.TLSConfig()
}

func configureTLSCertificate(tc *tls.Config, certFile, keyFile string) error {
	// certfile and keyfile are required
	if certFile == "" || keyFile == "" {
		return errors.New("tls: certificate and key files must be set")
	}

	var err error
	tc.Certificates = make([]tls.Certificate, 1)
	tc.Certificates[0], err = tls.LoadX509KeyPair(certFile, keyFile)
	return err
}

func buildHTTPServer(s *Server, tc *tls.Config) (*http.Server, error) {
	srv := &http.Server{
		Addr:              s.Addr,
		Handler:           s.Handler,
		TLSConfig:         tc,
		ReadTimeout:       s.ReadTimeout,
		ReadHeaderTimeout: s.ReadHeaderTimeout,
		WriteTimeout:      s.WriteTimeout,
		IdleTimeout:       s.IdleTimeout,
		MaxHeaderBytes:    s.MaxHeaderBytes,
		ConnState:         s.ConnStateHook,
		ErrorLog:          s.ErrorLog,
		BaseContext:       s.BaseContext,
		ConnContext:       s.ConnContext,
		HTTP2:             s.HTTP2Config,
		Protocols:         s.Protocols,
	}
	return srv, nil
}
